### ISSUE TITLE
How can I use this in local web app without internet?

### ISSUE THREAD

**Issue by lztz0022** [theajack/easy-icon#1]
Wonderful job! But how can I use this in a local web-app without internet?
I once used another icon font, which can be read from a local folder. Can easy-icon do like this?

**Comment by theajack** [comment]
Thank you for your attention! Now you can use offline mode in version 1.0.7, [mode details](https://github.com/theajack/easy-icon#212-offline-mode)
@lztz0022

**Comment by lztz0022** [comment]
> Thank you for your attention! Now you can use offline mode in version 1.0.7, [mode details](https://github.com/theajack/easy-icon#212-offline-mode)
> @lztz0022

Thanks for all of your guys' great work
